export enum MachineStatus {
    OPERATIONAL = "OPERATIONAL",
    UNDER_MAINTENANCE = "UNDER_MAINTENANCE",
    OUT_OF_ORDER = "OUT_OF_ORDER",
    IDLE = "IDLE",
    DECOMMISSIONED = "DECOMMISSIONED",
}
